### ISSUE TITLE
Ability for one instance to run against multiple hosts

### ISSUE THREAD

**Issue by billabongrob** [ThoreKr/cups_exporter#10]
It would be a nice added feature to allow this exporter to scan multiple hosts without having to run an instance on each server, similar to how blackbox exporter works.

**Comment by ThoreKr** [comment]
Thanks for contributing this idea. However, I'm sceptic this is a good idea to implement in this project.

After taking a look at the code again (it's been a while) a few questions came up

- should it just scrape a list of cupsds when the exporter is called?
- should the endpoints be actually configureable in prometheus scrape config? 
  - how are credentials supposed to be provided?

This requires a quite couple of changes to the way the exporter currently works.
If you wan't to contribute these, please feel free to, I unfortunately do not have the time at the moment to redesign the exporter.
