### ISSUE TITLE
Merge changes from tag v1.0.0 to master

### ISSUE THREAD

**Issue by JackN5y** [ThoreKr/cups_exporter#12]
Please merge changes from tag v1.0.0 to master. 
![image](https://github.com/ThoreKr/cups_exporter/assets/144685141/7507fcf7-c593-446a-811f-4713e02c1a76)

**Comment by ThoreKr** [comment]
There are no changes to merge. The commits are part of the branch. I do not recall what went wrong there with the commit history or why the commit hashes differ, but there shouldn't be any missing changes.
