### ISSUE TITLE
Please publish a license

### ISSUE THREAD

**Issue by mmahut** [ThoreKr/cups_exporter#2]
As we are shipping this software in NixOS, we would like to kindly ask to publish a license as upstream. Thank you.

**Comment by ThoreKr** [comment]
I've added a license though I would not recommend packaging this exporter, considering the way it is implemented and the code quality...

**Comment by mmahut** [comment]
Thank you, what are you primary concerns?

**Comment by ThoreKr** [comment]
The way it scrapes (every 5 seconds in a while true loop) is not really the way it should be done.

It was more of a quick&dirty solution to get it working and documentation wasn't that evolved on how to build a handler to do the gathering on scrape.
